services:
  database:
    image: postgres:15-alpine
    container_name: innovera-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: innovera
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d innovera" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - innovera-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: innovera-backend
    ports:
      - "5001:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/innovera
      - PORT=3000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - innovera-network

volumes:
  postgres_data:


networks:
  innovera-network:
    driver: bridge
